Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "private_network", ip: "192.168.0.11"

  config.vm.provision "shell", inline: <<-SHELL
    # Mise à jour des packages et installation de curl
    apt-get update
    apt-get install -y curl

    # Installation de nmap
    apt-get install -y nmap
  SHELL
end
